version: "3.5"

services:
  nextjs:
    image: node:14
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm install && npm run dev"
    #    command: sh -c "while true; do sleep 2; done"
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
